name: Jekyll-Grunt-Kickass
description: "a template for jekyll sites developed with the help of grunt and bower"
markdown: redcarpet
pygments: true

destination: ./_site

permalink: none

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components
  - package.json
  - node_modules
