name: MAIWOLF PHOTOGRAPHY
markdown: redcarpet
pygments: true

destination: ./_site

permalink: none

exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components
  - package.json
  - node_modules
